---
- hosts: all

  tasks:
    - name: Install openscap-scanner
      yum:
        name: openscap-scanner
        state: present
    - name: copy openscap data stream file to target client
      copy:
        src: /rhel7isorpms/rhel-7.ds.xml
        dest: /tmp/rhel-7.ds.xml
    - name: Start scan vulnerability RHEL
      shell: oscap xccdf eval --results /tmp/results.xml --report /tmp/vulnerability-report.html /tmp/rhel-7.ds.xml 
      async: 120
      poll: 10
      register: result
      ignore_errors: true
    - name: change result file permission
      shell: chmod 777 /tmp/vulnerability-report.html
    - name: fetch openscap report
      fetch:
        src: /tmp/vulnerability-report.html
        dest: /var/www/html/openscap/
        flat: yes
