---
- hosts: local
  tasks:
    - name: generate password
      shell: echo -n 'root:'$(openssl passwd -1 {{ password }}) > /root/mypasswd
    - name: change password
      shell: chpasswd -e < /root/mypasswd
    - name: delete temporary file
      shell: rm -f /root/mypasswd
